// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: parking.proto

package protos

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ParkingService_GetBox_FullMethodName                = "/parking.ParkingService/GetBox"
	ParkingService_ListBoxes_FullMethodName             = "/parking.ParkingService/ListBoxes"
	ParkingService_UpdateBoxAvailability_FullMethodName = "/parking.ParkingService/UpdateBoxAvailability"
	ParkingService_StreamBoxUpdates_FullMethodName      = "/parking.ParkingService/StreamBoxUpdates"
)

// ParkingServiceClient is the client API for ParkingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The service definition for the gRPC server and client
type ParkingServiceClient interface {
	// Returns a specific box by its ID
	GetBox(ctx context.Context, in *GetBoxRequest, opts ...grpc.CallOption) (*Box, error)
	// Returns all boxes (useful for initial dashboard load)
	ListBoxes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListBoxesResponse, error)
	// Updates a box's status and returns the updated state
	UpdateBoxAvailability(ctx context.Context, in *UpdateBoxRequest, opts ...grpc.CallOption) (*Box, error)
	// Server-side stream to push updates to the dashboard in real-time
	StreamBoxUpdates(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Box], error)
}

type parkingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParkingServiceClient(cc grpc.ClientConnInterface) ParkingServiceClient {
	return &parkingServiceClient{cc}
}

func (c *parkingServiceClient) GetBox(ctx context.Context, in *GetBoxRequest, opts ...grpc.CallOption) (*Box, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Box)
	err := c.cc.Invoke(ctx, ParkingService_GetBox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) ListBoxes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListBoxesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBoxesResponse)
	err := c.cc.Invoke(ctx, ParkingService_ListBoxes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) UpdateBoxAvailability(ctx context.Context, in *UpdateBoxRequest, opts ...grpc.CallOption) (*Box, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Box)
	err := c.cc.Invoke(ctx, ParkingService_UpdateBoxAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) StreamBoxUpdates(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Box], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ParkingService_ServiceDesc.Streams[0], ParkingService_StreamBoxUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[empty.Empty, Box]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ParkingService_StreamBoxUpdatesClient = grpc.ServerStreamingClient[Box]

// ParkingServiceServer is the server API for ParkingService service.
// All implementations must embed UnimplementedParkingServiceServer
// for forward compatibility.
//
// The service definition for the gRPC server and client
type ParkingServiceServer interface {
	// Returns a specific box by its ID
	GetBox(context.Context, *GetBoxRequest) (*Box, error)
	// Returns all boxes (useful for initial dashboard load)
	ListBoxes(context.Context, *empty.Empty) (*ListBoxesResponse, error)
	// Updates a box's status and returns the updated state
	UpdateBoxAvailability(context.Context, *UpdateBoxRequest) (*Box, error)
	// Server-side stream to push updates to the dashboard in real-time
	StreamBoxUpdates(*empty.Empty, grpc.ServerStreamingServer[Box]) error
	mustEmbedUnimplementedParkingServiceServer()
}

// UnimplementedParkingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParkingServiceServer struct{}

func (UnimplementedParkingServiceServer) GetBox(context.Context, *GetBoxRequest) (*Box, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBox not implemented")
}
func (UnimplementedParkingServiceServer) ListBoxes(context.Context, *empty.Empty) (*ListBoxesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBoxes not implemented")
}
func (UnimplementedParkingServiceServer) UpdateBoxAvailability(context.Context, *UpdateBoxRequest) (*Box, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBoxAvailability not implemented")
}
func (UnimplementedParkingServiceServer) StreamBoxUpdates(*empty.Empty, grpc.ServerStreamingServer[Box]) error {
	return status.Error(codes.Unimplemented, "method StreamBoxUpdates not implemented")
}
func (UnimplementedParkingServiceServer) mustEmbedUnimplementedParkingServiceServer() {}
func (UnimplementedParkingServiceServer) testEmbeddedByValue()                        {}

// UnsafeParkingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParkingServiceServer will
// result in compilation errors.
type UnsafeParkingServiceServer interface {
	mustEmbedUnimplementedParkingServiceServer()
}

func RegisterParkingServiceServer(s grpc.ServiceRegistrar, srv ParkingServiceServer) {
	// If the following call panics, it indicates UnimplementedParkingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParkingService_ServiceDesc, srv)
}

func _ParkingService_GetBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBoxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).GetBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_GetBox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).GetBox(ctx, req.(*GetBoxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_ListBoxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).ListBoxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_ListBoxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).ListBoxes(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_UpdateBoxAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBoxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).UpdateBoxAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_UpdateBoxAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).UpdateBoxAvailability(ctx, req.(*UpdateBoxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_StreamBoxUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ParkingServiceServer).StreamBoxUpdates(m, &grpc.GenericServerStream[empty.Empty, Box]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ParkingService_StreamBoxUpdatesServer = grpc.ServerStreamingServer[Box]

// ParkingService_ServiceDesc is the grpc.ServiceDesc for ParkingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParkingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parking.ParkingService",
	HandlerType: (*ParkingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBox",
			Handler:    _ParkingService_GetBox_Handler,
		},
		{
			MethodName: "ListBoxes",
			Handler:    _ParkingService_ListBoxes_Handler,
		},
		{
			MethodName: "UpdateBoxAvailability",
			Handler:    _ParkingService_UpdateBoxAvailability_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBoxUpdates",
			Handler:       _ParkingService_StreamBoxUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "parking.proto",
}
