// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: parking.proto

package protos

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The core data structure representing a parking spot
type Box struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BoxId int32                  `protobuf:"varint,2,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	// Coordinates
	X1            int32                `protobuf:"varint,3,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            int32                `protobuf:"varint,4,opt,name=y1,proto3" json:"y1,omitempty"`
	X2            int32                `protobuf:"varint,5,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2            int32                `protobuf:"varint,6,opt,name=y2,proto3" json:"y2,omitempty"`
	X3            int32                `protobuf:"varint,7,opt,name=x3,proto3" json:"x3,omitempty"`
	Y3            int32                `protobuf:"varint,8,opt,name=y3,proto3" json:"y3,omitempty"`
	X4            int32                `protobuf:"varint,9,opt,name=x4,proto3" json:"x4,omitempty"`
	Y4            int32                `protobuf:"varint,10,opt,name=y4,proto3" json:"y4,omitempty"`
	Availability  int32                `protobuf:"varint,11,opt,name=availability,proto3" json:"availability,omitempty"` // 0 = available, 1 = occupied
	UpdatedAt     *timestamp.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Box) Reset() {
	*x = Box{}
	mi := &file_parking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Box) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Box) ProtoMessage() {}

func (x *Box) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Box.ProtoReflect.Descriptor instead.
func (*Box) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{0}
}

func (x *Box) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Box) GetBoxId() int32 {
	if x != nil {
		return x.BoxId
	}
	return 0
}

func (x *Box) GetX1() int32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *Box) GetY1() int32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *Box) GetX2() int32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *Box) GetY2() int32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

func (x *Box) GetX3() int32 {
	if x != nil {
		return x.X3
	}
	return 0
}

func (x *Box) GetY3() int32 {
	if x != nil {
		return x.Y3
	}
	return 0
}

func (x *Box) GetX4() int32 {
	if x != nil {
		return x.X4
	}
	return 0
}

func (x *Box) GetY4() int32 {
	if x != nil {
		return x.Y4
	}
	return 0
}

func (x *Box) GetAvailability() int32 {
	if x != nil {
		return x.Availability
	}
	return 0
}

func (x *Box) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request/Response messages for gRPC methods
type GetBoxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoxId         int32                  `protobuf:"varint,1,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoxRequest) Reset() {
	*x = GetBoxRequest{}
	mi := &file_parking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoxRequest) ProtoMessage() {}

func (x *GetBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoxRequest.ProtoReflect.Descriptor instead.
func (*GetBoxRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{1}
}

func (x *GetBoxRequest) GetBoxId() int32 {
	if x != nil {
		return x.BoxId
	}
	return 0
}

type UpdateBoxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoxId         int32                  `protobuf:"varint,1,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	Availability  int32                  `protobuf:"varint,2,opt,name=availability,proto3" json:"availability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoxRequest) Reset() {
	*x = UpdateBoxRequest{}
	mi := &file_parking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoxRequest) ProtoMessage() {}

func (x *UpdateBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoxRequest.ProtoReflect.Descriptor instead.
func (*UpdateBoxRequest) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateBoxRequest) GetBoxId() int32 {
	if x != nil {
		return x.BoxId
	}
	return 0
}

func (x *UpdateBoxRequest) GetAvailability() int32 {
	if x != nil {
		return x.Availability
	}
	return 0
}

type ListBoxesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boxes         []*Box                 `protobuf:"bytes,1,rep,name=boxes,proto3" json:"boxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBoxesResponse) Reset() {
	*x = ListBoxesResponse{}
	mi := &file_parking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBoxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBoxesResponse) ProtoMessage() {}

func (x *ListBoxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBoxesResponse.ProtoReflect.Descriptor instead.
func (*ListBoxesResponse) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{3}
}

func (x *ListBoxesResponse) GetBoxes() []*Box {
	if x != nil {
		return x.Boxes
	}
	return nil
}

var File_parking_proto protoreflect.FileDescriptor

const file_parking_proto_rawDesc = "" +
	"\n" +
	"\rparking.proto\x12\aparking\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x8b\x02\n" +
	"\x03Box\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x15\n" +
	"\x06box_id\x18\x02 \x01(\x05R\x05boxId\x12\x0e\n" +
	"\x02x1\x18\x03 \x01(\x05R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x04 \x01(\x05R\x02y1\x12\x0e\n" +
	"\x02x2\x18\x05 \x01(\x05R\x02x2\x12\x0e\n" +
	"\x02y2\x18\x06 \x01(\x05R\x02y2\x12\x0e\n" +
	"\x02x3\x18\a \x01(\x05R\x02x3\x12\x0e\n" +
	"\x02y3\x18\b \x01(\x05R\x02y3\x12\x0e\n" +
	"\x02x4\x18\t \x01(\x05R\x02x4\x12\x0e\n" +
	"\x02y4\x18\n" +
	" \x01(\x05R\x02y4\x12\"\n" +
	"\favailability\x18\v \x01(\x05R\favailability\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"&\n" +
	"\rGetBoxRequest\x12\x15\n" +
	"\x06box_id\x18\x01 \x01(\x05R\x05boxId\"M\n" +
	"\x10UpdateBoxRequest\x12\x15\n" +
	"\x06box_id\x18\x01 \x01(\x05R\x05boxId\x12\"\n" +
	"\favailability\x18\x02 \x01(\x05R\favailability\"7\n" +
	"\x11ListBoxesResponse\x12\"\n" +
	"\x05boxes\x18\x01 \x03(\v2\f.parking.BoxR\x05boxes2\xff\x01\n" +
	"\x0eParkingService\x12.\n" +
	"\x06GetBox\x12\x16.parking.GetBoxRequest\x1a\f.parking.Box\x12?\n" +
	"\tListBoxes\x12\x16.google.protobuf.Empty\x1a\x1a.parking.ListBoxesResponse\x12@\n" +
	"\x15UpdateBoxAvailability\x12\x19.parking.UpdateBoxRequest\x1a\f.parking.Box\x12:\n" +
	"\x10StreamBoxUpdates\x12\x16.google.protobuf.Empty\x1a\f.parking.Box0\x01B-Z+github.com/spotwatchllc/parking-dash/protosb\x06proto3"

var (
	file_parking_proto_rawDescOnce sync.Once
	file_parking_proto_rawDescData []byte
)

func file_parking_proto_rawDescGZIP() []byte {
	file_parking_proto_rawDescOnce.Do(func() {
		file_parking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parking_proto_rawDesc), len(file_parking_proto_rawDesc)))
	})
	return file_parking_proto_rawDescData
}

var file_parking_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_parking_proto_goTypes = []any{
	(*Box)(nil),                 // 0: parking.Box
	(*GetBoxRequest)(nil),       // 1: parking.GetBoxRequest
	(*UpdateBoxRequest)(nil),    // 2: parking.UpdateBoxRequest
	(*ListBoxesResponse)(nil),   // 3: parking.ListBoxesResponse
	(*timestamp.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*empty.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_parking_proto_depIdxs = []int32{
	4, // 0: parking.Box.updated_at:type_name -> google.protobuf.Timestamp
	0, // 1: parking.ListBoxesResponse.boxes:type_name -> parking.Box
	1, // 2: parking.ParkingService.GetBox:input_type -> parking.GetBoxRequest
	5, // 3: parking.ParkingService.ListBoxes:input_type -> google.protobuf.Empty
	2, // 4: parking.ParkingService.UpdateBoxAvailability:input_type -> parking.UpdateBoxRequest
	5, // 5: parking.ParkingService.StreamBoxUpdates:input_type -> google.protobuf.Empty
	0, // 6: parking.ParkingService.GetBox:output_type -> parking.Box
	3, // 7: parking.ParkingService.ListBoxes:output_type -> parking.ListBoxesResponse
	0, // 8: parking.ParkingService.UpdateBoxAvailability:output_type -> parking.Box
	0, // 9: parking.ParkingService.StreamBoxUpdates:output_type -> parking.Box
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_parking_proto_init() }
func file_parking_proto_init() {
	if File_parking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parking_proto_rawDesc), len(file_parking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parking_proto_goTypes,
		DependencyIndexes: file_parking_proto_depIdxs,
		MessageInfos:      file_parking_proto_msgTypes,
	}.Build()
	File_parking_proto = out.File
	file_parking_proto_goTypes = nil
	file_parking_proto_depIdxs = nil
}
